import type { ObjectId } from "mongodb";
import type { Place as GooglePlace } from "@googlemaps/google-maps-services-js";

/*
 Note: _id is optional because _id of type ObjectId is automatically 
 generated by mongo upon an initial insertion
 */
export interface User {
	_id?: ObjectId;
	email: string;
	hash: string;
	dateEdited?: Date;
	token: string;
	dateTokenCreated: Date;
}

export interface Rating {
	_id?: ObjectId;
	userID: ObjectId;
	placeID: GooglePlace["place_id"];
	guideDogFriendly: number | null;
	isMenuAccessible: boolean | null; // null bc they may not be able to give a yes/no answer
	noiseLevel: number | null;
	lighting: number | null;
	isStaffHelpful: boolean | null;
	isBathroomOnEntranceFloor: boolean | null;
	isContactlessPaymentOffered: boolean | null;
	areThereStairs: boolean | null;
	spacing: number | null;
	comment: string | null;
	dateCreated: Date;
	dateEdited?: Date;
}

export interface Place {
	_id: GooglePlace["place_id"];
	avgBraille: number | null;
	avgFontReadability: number | null;
	avgStaffHelpfulness: number | null;
	avgNavigability: number | null;
	avgGuideDogFriendly: number | null;
	promotion: {
		monthly_budget: number;
		max_cpc: number;
	};
}

export type PlaceWithA11yAndPromo = GooglePlace & {
	accessibilityData: Place;
	promoMonth?: PromotionMonth;
	isValidPromo?: boolean;
	isPromoted?: boolean;
	spend_amount?: number;
};

export interface PromotionMonth {
	_id?: ObjectId;
	placeID: GooglePlace["place_id"];
	month: number;
	year: number;
	totalSpent: number;
}
