import type { ObjectId } from "mongodb";

/*
 Note: _id is optional because _id of type ObjectId is automatically 
 generated by mongo upon an initial insertion
 */
export interface User {
	_id?: ObjectId;
	email: string;
	hash: string;
	dateEdited?: Date;
	token: string;
	dateTokenCreated: Date;
}
